### ISSUE TITLE
There are some bugs in run_coqa_dataset_utils.py

### ISSUE THREAD

**Issue by kugwzk** [adamluo1995/Bert4CoQA#2]
Hi, @adamluo1995 . I ran your code at the master version, but I found some bugs because the yes_logit/no_logit/unk_logit but you used cls_logit in run_coqa_dataset_utils.py. But when I used your old version code I got a too low F1 and EM (5.6/7.9), I checked the path of eval model to make sure the model is fine-tuned. If because I used a low version of pytorch_pretrained_bert? My version is 0.3.0.

**Comment by adamluo1995** [comment]
plz forget pytorch_pretrained_bert and used BERT implement i pack inside depo.

**Comment by kugwzk** [comment]
@adamluo1995 I have fixed that bug btw thanks a lot~
