### ISSUE TITLE
tf_model.h5 cannot found

### ISSUE THREAD

**Issue by dhuy237** [adamluo1995/Bert4CoQA#5]
I have this error:
`OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory ./bert_model/ or from_tf set to False`

About `pytorch_model.bin` and `model.ckpt.index` file, I can found it in  [SDNet](https://github.com/microsoft/SDNet) and [google-research/bert](https://github.com/google-research/bert#pre-trained-models) repository.
But I don't know where to get the `tf_model.h5` file.
Can you tell me where to get it?
Thanks.

**Comment by adamluo1995** [comment]
I will leave models url on README.

**Comment by khoathecoolest** [comment]
@adamluo1995 Thank you.

**Comment by dhuy237** [comment]
@adamluo1995 Thank you.
